import { Award, Trophy, CheckCircle2, AlertCircle, Sparkles } from "lucide-react";

function HeroSection({ report }) {
    const getRecommendationBadge = () => {
        const recommendation = report.recommendation?.toLowerCase() || "";

        if (recommendation.includes("strong")) {
            return {
                label: report.recommendation || "Strong Hire",
                bg: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
                icon: <Trophy size={16} className="text-emerald-400" />
            };
        }

        if (recommendation.includes("hire") || recommendation.includes("recommend")) {
            return {
                label: report.recommendation || "Hire Recommended",
                bg: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
                icon: <CheckCircle2 size={16} className="text-cyan-400" />
            };
        }

        return {
            label: report.recommendation || "Needs Improvement",
            bg: "bg-amber-500/20 text-amber-300 border-amber-500/30",
            icon: <AlertCircle size={16} className="text-amber-400" />
        };
    };

    const recStyle = getRecommendationBadge();
    const overallScore = typeof report.overall_score === "number" ? report.overall_score : null;

    return (
        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-blue-950/80 via-indigo-950/80 to-purple-950/80 border border-white/[0.1] p-6 sm:p-10 text-white shadow-2xl backdrop-blur-xl mb-8">
            {/* Top accent glow line */}
            <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-cyan-400/50 to-transparent" />
            <div className="pointer-events-none absolute -right-16 -bottom-16 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl" />
            <div className="pointer-events-none absolute -left-16 -top-16 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl" />

            <div className="relative z-10 space-y-6">
                {/* Header Badge */}
                <div className="flex flex-wrap items-center justify-between gap-3">
                    <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-300 text-xs font-black">
                        <Award size={15} />
                        <span>AI Performance Evaluation Report</span>
                    </div>

                    <div className={`inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-black border shadow-md ${recStyle.bg}`}>
                        {recStyle.icon}
                        <span>{recStyle.label}</span>
                    </div>
                </div>

                {/* Main Role Title */}
                <div>
                    <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight text-white leading-tight">
                        {report.interview_title || report.job_title || report.role || "AI Interview Assessment"}
                    </h1>
                    <p className="mt-2 text-slate-300 text-xs sm:text-sm max-w-2xl font-medium leading-relaxed">
                        Comprehensive evaluation report generated by AI analyzer, highlighting technical mastery, communication clarity, confidence metrics, and targeted improvement strategies.
                    </p>
                </div>

                {/* Score & Key Metrics Grid */}
                <div className="grid gap-4 sm:grid-cols-3 pt-2">
                    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-5 backdrop-blur-md flex items-center justify-between">
                        <div>
                            <p className="text-[10px] uppercase font-black tracking-wider text-slate-400">Overall Score</p>
                            <p className="mt-1 text-3xl sm:text-4xl font-black text-white">
                                {overallScore !== null ? `${overallScore}%` : "N/A"}
                            </p>
                            <p className="text-[11px] text-cyan-400 font-semibold mt-0.5">Aggregated AI Grade</p>
                        </div>
                        <div className="p-3 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400">
                            <Sparkles size={24} />
                        </div>
                    </div>

                    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-5 backdrop-blur-md flex items-center justify-between">
                        <div>
                            <p className="text-[10px] uppercase font-black tracking-wider text-slate-400">Target Role</p>
                            <p className="mt-1 text-lg font-black text-white truncate max-w-[150px]">
                                {report.job_title || report.role || "General"}
                            </p>
                            <p className="text-[11px] text-slate-400 font-semibold mt-0.5">Job Level Assessment</p>
                        </div>
                        <div className="p-3 rounded-2xl bg-purple-500/10 border border-purple-500/20 text-purple-400">
                            <Award size={24} />
                        </div>
                    </div>

                    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-5 backdrop-blur-md flex items-center justify-between">
                        <div>
                            <p className="text-[10px] uppercase font-black tracking-wider text-slate-400">Decision Outcome</p>
                            <p className="mt-1 text-lg font-black text-emerald-400 truncate max-w-[150px]">
                                {report.recommendation || "Pending Review"}
                            </p>
                            <p className="text-[11px] text-emerald-400/80 font-semibold mt-0.5">AI Recommendation</p>
                        </div>
                        <div className="p-3 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400">
                            <Trophy size={24} />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default HeroSection;